// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	auth "pvz/internal/models/auth"

	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// DummyLogin provides a mock function with given fields: req
func (_m *AuthService) DummyLogin(req auth.DummyLoginRequest) (string, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for DummyLogin")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(auth.DummyLoginRequest) (string, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(auth.DummyLoginRequest) string); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(auth.DummyLoginRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_DummyLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DummyLogin'
type AuthService_DummyLogin_Call struct {
	*mock.Call
}

// DummyLogin is a helper method to define mock.On call
//   - req auth.DummyLoginRequest
func (_e *AuthService_Expecter) DummyLogin(req interface{}) *AuthService_DummyLogin_Call {
	return &AuthService_DummyLogin_Call{Call: _e.mock.On("DummyLogin", req)}
}

func (_c *AuthService_DummyLogin_Call) Run(run func(req auth.DummyLoginRequest)) *AuthService_DummyLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(auth.DummyLoginRequest))
	})
	return _c
}

func (_c *AuthService_DummyLogin_Call) Return(_a0 string, _a1 error) *AuthService_DummyLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_DummyLogin_Call) RunAndReturn(run func(auth.DummyLoginRequest) (string, error)) *AuthService_DummyLogin_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: req
func (_m *AuthService) Login(req auth.LoginRequest) (string, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(auth.LoginRequest) (string, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(auth.LoginRequest) string); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(auth.LoginRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - req auth.LoginRequest
func (_e *AuthService_Expecter) Login(req interface{}) *AuthService_Login_Call {
	return &AuthService_Login_Call{Call: _e.mock.On("Login", req)}
}

func (_c *AuthService_Login_Call) Run(run func(req auth.LoginRequest)) *AuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(auth.LoginRequest))
	})
	return _c
}

func (_c *AuthService_Login_Call) Return(_a0 string, _a1 error) *AuthService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_Login_Call) RunAndReturn(run func(auth.LoginRequest) (string, error)) *AuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: req
func (_m *AuthService) Register(req auth.RegisterRequest) (auth.RegisterResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 auth.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(auth.RegisterRequest) (auth.RegisterResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(auth.RegisterRequest) auth.RegisterResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(auth.RegisterResponse)
	}

	if rf, ok := ret.Get(1).(func(auth.RegisterRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - req auth.RegisterRequest
func (_e *AuthService_Expecter) Register(req interface{}) *AuthService_Register_Call {
	return &AuthService_Register_Call{Call: _e.mock.On("Register", req)}
}

func (_c *AuthService_Register_Call) Run(run func(req auth.RegisterRequest)) *AuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(auth.RegisterRequest))
	})
	return _c
}

func (_c *AuthService_Register_Call) Return(_a0 auth.RegisterResponse, _a1 error) *AuthService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_Register_Call) RunAndReturn(run func(auth.RegisterRequest) (auth.RegisterResponse, error)) *AuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
